openapi: 3.0.0
info:
  title: ArgentBank - Phase 2
  description: API allowing the user to retrieve its own account and account details as well as transactions from the server
  version: 1.0.0
servers:
  - url: http://localhost:3001/api/v1/
    description: Production server
  - url: http://localhost:3001/api/test/v1/
    description: Staging server
paths:
  /user/accounts:
    get:
      summary: Get accounts for a given user
      parameters:
        - name: Token
          in: header
          description: JWT token from user connection
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: number
                balance: number
                type: string
                card number: string
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                error: "Invalid request parameters"
        '404':
          description: Not Found
          content:
            application/json:
              example:
                error: "User not found or has no accounts"

  /user/account/details/{accountId}:
    get:
      summary: Get account details
      parameters:
        - name: Token
          in: header
          description: JWT token from user connection
          required: true
          schema:
            type: string
        - name: accountId
          in: path
          description: ID of the account the user wants to retrieve details for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                id: number
                date: dd/mm/yyyy
                description: text
                amount: number
                balance: number
                type: string
                category: string
                note: string
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                error: "Invalid request parameters"
        '404':
          description: Not Found
          content:
            application/json:
              example:
                error: "Account not found"

    patch:
      summary: Update account details
      description: Update data in transaction note or category slot
      parameters:
        - name: Token
          in: header
          description: JWT token from user connection
          required: true
          schema:
            type: string
        - name: accountId
          in: path
          description: ID of the account to update
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            example:
              note: string
              category: string
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                error: "Invalid request parameters"
        '404':
          description: Not Found
          content:
            application/json:
              example:
                error: "Account not found"
